"""Format-neutral document model and semantic document contracts."""

from .model import (
    BlockNode,
    Cell,
    Comment,
    Document,
    Endnote,
    Field,
    FieldSpec,
    Footnote,
    Hyperlink,
    ImageBlock,
    ImageInline,
    ImageSpec,
    InlineNode,
    LineBreak,
    ListBlock,
    ListItem,
    Math,
    OpaqueBlock,
    OpaqueInline,
    Paragraph,
    Quote,
    Row,
    SectionBreak,
    SourceContext,
    StyleRef,
    StyledInline,
    Table,
    Todo,
    Text,
    Bookmark,
    paragraph_from_text,
    paragraph_text,
)
from .contracts import Attachment, ExportRequest, ImportResult, SidecarHandle
from .diagnostics import Diagnostic, DiagnosticCode, Severity, SourceReference
from .formatting import ParagraphFormat, RunFormat
from .identity import NodeId
from .roles import CharacterRole, ListRole, ParagraphRole
from .semantic import semantic_equal, semantic_key

__all__ = [
    "BlockNode",
    "Attachment",
    "Bookmark",
    "Cell",
    "CharacterRole",
    "Comment",
    "Diagnostic",
    "DiagnosticCode",
    "Document",
    "Endnote",
    "ExportRequest",
    "Field",
    "FieldSpec",
    "Footnote",
    "Hyperlink",
    "ImageBlock",
    "ImageInline",
    "ImageSpec",
    "ImportResult",
    "InlineNode",
    "LineBreak",
    "ListBlock",
    "ListItem",
    "ListRole",
    "Math",
    "OpaqueBlock",
    "OpaqueInline",
    "Paragraph",
    "Quote",
    "ParagraphRole",
    "ParagraphFormat",
    "NodeId",
    "Row",
    "RunFormat",
    "SectionBreak",
    "SidecarHandle",
    "SourceContext",
    "StyleRef",
    "Severity",
    "SourceReference",
    "StyledInline",
    "Table",
    "Todo",
    "Text",
    "paragraph_from_text",
    "paragraph_text",
    "semantic_equal",
    "semantic_key",
]
